package com.twitter.clone.model;

// Generated May 19, 2015 11:13:01 AM by Hibernate Tools 4.3.1

/**
 * Followee generated by hbm2java
 */
public class Followee implements java.io.Serializable {

	private Integer id;
	private User user;
	private String name;

	public Followee() {
	}

	public Followee(User user, String name) {
		this.user = user;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
