package com.twitter.clone.model;

// Generated May 19, 2015 11:13:01 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Saying generated by hbm2java
 */
public class Saying implements java.io.Serializable {

	private Integer id;
	private User user;
	private String saying;
	private Date lastUpdate;

	public Saying() {
	}

	public Saying(User user, String saying, Date lastUpdate) {
		this.user = user;
		this.saying = saying;
		this.lastUpdate = lastUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSaying() {
		return this.saying;
	}

	public void setSaying(String saying) {
		this.saying = saying;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
