package com.twitter.clone.model;

// Generated May 19, 2015 11:13:01 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Person person;
	private String name;
	private String password;
	private Set followees = new HashSet(0);
	private Set sayings = new HashSet(0);

	public User() {
	}

	public User(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public User(Person person, String name, String password, Set followees,
			Set sayings) {
		this.person = person;
		this.name = name;
		this.password = password;
		this.followees = followees;
		this.sayings = sayings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getFollowees() {
		return this.followees;
	}

	public void setFollowees(Set followees) {
		this.followees = followees;
	}

	public Set getSayings() {
		return this.sayings;
	}

	public void setSayings(Set sayings) {
		this.sayings = sayings;
	}

}
